(HDRP) NYC-Like City Buildings Set (PBR)
(HDRP) NYC-Like City Buildings Set (PBR).meta

/Assets/Simple city plain/scene
/Assets/Simple city plain/scene.meta

/Assets/(HDRP) NYC-Like City Buildings Set (PBR)
/Assets/(HDRP) NYC-Like City Buildings Set (PBR).meta

